"use client";

import { Download } from "lucide-react";
import { Button } from "../ui/button";

export default function DownloadSummaryButton({
  title,
  summary_text,
  file_name,
  created_at,
}: {
  title: string;
  summary_text: string;
  file_name: string;
  created_at: string;
}) {
  const handleDownload = () => {
    const summaryContent = `# ${title}

Generated Summary
Generated on: ${new Date(created_at).toLocaleDateString()}

	${summary_text}

	Original File: ${file_name}
	Generated by Necto
	`;
    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/\s+/g, "_")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
  return (
    <Button
      className="h-8 px-3 text-rose-50 hover:text-rose-900 hover:bg-rose-50"
      onClick={handleDownload}
    >
      <Download className="h-4 w-4 mr-1" />
      Download Summary
    </Button>
  );
}
